site_name: Philipp's Journal
site_description: 'A collection of work & thoughts'
site_author: 'Philipp Ahmann'
site_dir: public

repo_url: https://github.com/pahmann/journal

nav:
    - Home: index.md

theme:
  name: 'material'
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.footer
    - navigation.top

plugins:
  - search

markdown_extensions:
  - attr_list
  - pymdownx.pathconverter:
      absolute: true
  - pymdownx.tilde
